repository:
  # See https://github.com/probot/settings for documentation
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - test
          - security-audit
          - lint
      enforce_admins: true
      required_linear_history: true
      require_signed_commits: true
      allow_force_pushes: false
      allow_deletions: false
